version: "3.1"
services:
  web:
    build: .
    links:
      - otel-collector
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # Configure Open Telemetry Collector Url
      OTLP__ENDPOINT: "http://otel-collector:4317"

    ports:
      - "8000:80"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.19.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver

  #datadog-agent:
  #  image: "gcr.io/datadoghq/agent:7"
  #  links:
  #    - web
  #  environment:
  #    DD_API_KEY: "2f79ac1503bf67bb403fb09639d4677a"
  #    DD_SITE: "datadoghq.com"
  #    DD_TRACE_ENABLED: "false"
  #    DD_APM_ENABLED: "false"
  #    DD_APM_NON_LOCAL_TRAFFIC: "false"
  #    DD_LOGS_ENABLED: "true"
  #    DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
  #    DD_CONTAINER_EXCLUDE_LOGS: "name:datadog-agent"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - /proc/:/host/proc/:ro
  #    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  #  depends_on:
  #    - web
